function plotRocketBody
%CREATEFIGURE

%  Auto-generated by MATLAB on 27-Oct-2017 18:38:44

% Create figure
figure1 = figure;

% Create line
annotation(figure1,'line',[0.43 0.40],...
    [0.33 0.28]);

% Create line
annotation(figure1,'line',[0.50 0.55],...
    [0.33 0.29]);

% Create line
annotation(figure1,'line',[0.43 0.50],...
    [0.65 0.65]);

% Create line
annotation(figure1,'line',[0.43 0.43],...
    [0.65 0.13]);

% Create line
annotation(figure1,'line',[0.50 0.50],...
    [0.65 0.13]);

% Create line
annotation(figure1,'line',[0.48 0.50],...
    [0.86 0.66]);

% Create line
annotation(figure1,'line',[0.43 0.48],...
    [0.66 0.86]);

% Create line
annotation(figure1,'line',[0.43 0.50],...
    [0.12 0.12]);

% Create line
annotation(figure1,'line',[0.47 0.47],...
    [0.22 0.15]);

% Create line
annotation(figure1,'line',[0.50 0.55],...
    [0.22 0.20]);

% Create line
annotation(figure1,'line',[0.40 0.43],...
    [0.20 0.22]);

% Create line
annotation(figure1,'line',[0.55 0.55],...
    [0.19 0.15]);

% Create line
annotation(figure1,'line',[0.40 0.40],...
    [0.2 0.16]);

% Create line
annotation(figure1,'line',[0.50 0.55],...
    [0.15 0.15]);

% Create line
annotation(figure1,'line',[0.40 0.43],...
    [0.15 0.15]);

