% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Nov-2017 15:01:45
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('dataTestFlight07_10_17.mat');

axG = saveVarsMat.axG; % <542965x1 double> too many elements

ayG = saveVarsMat.ayG; % <542965x1 double> too many elements

azG = saveVarsMat.azG; % <542965x1 double> too many elements

gx = saveVarsMat.gx; % <542965x1 double> too many elements

gy = saveVarsMat.gy; % <542965x1 double> too many elements

gz = saveVarsMat.gz; % <542965x1 double> too many elements

mx = saveVarsMat.mx; % <542965x1 double> too many elements

my = saveVarsMat.my; % <542965x1 double> too many elements

mz = saveVarsMat.mz; % <542965x1 double> too many elements

temp = saveVarsMat.temp; % <542965x1 double> too many elements

clear saveVarsMat;
